### ISSUE TITLE
Clay oven affects temperature while inactive

### ISSUE THREAD

**Issue by SigurdCole** [JayAvery/jjmod#4]
Hi!

I fired up my clay oven to do some early copper smelting, but I noticed that it's stayed hot. It may be because there's some unsmelted ore still in there, I haven't tested yet. I have an archive save if that would be useful.

Cheers!

**Comment by averixus** [comment]
This is currently the intended behaviour. :) Clay ovens and stone furnaces produce heat constantly, whereas campfires and pot fires have to be fueled in order to produce heat. That's also why campfires and pot fires use fuel constantly even if they don't have an input: so that they can be used as a heater without actually cooking.
